export default [
  "",
  {
    title: "知识碎片",
    collapsable: false,
    children: [
      "4 种方法，快速初始化 Java 项目.md",
      "使用后端代码生成器，提高开发效率.md",
      "前端必学的开发框架，Ant Design Pro.md",
      "后端如何编写单元测试？ .md",
      "后端项目经典分层架构介绍.md",
      "如何高效测试接口？自动生成接口文档.md",
      "开发企业微信群机器人，实现定时提醒.md",
      "【设计模式】装饰者模式，及其在JDK源码中的应用.md",
      "用四种锁实现加入队伍功能(伙伴匹配系统).md",
      "用@Validated注解实现非空校验.md",
      "使用第三方服务(宝塔)快速部署项目.md",
      "RESTful 接口实现与测试( Spring Boot ).md",
      "快速学会为开源项目做贡献.md",
      "整合Spring JDBC操作数据库.md",
      "Maven 中央仓库发包流程.md",
      "Nacos 配置中心搭建.md",
      "Bean 拷贝之 MapStruct.md",
      "如何快速忽略 Git 文件提交？.md",
      "EasyExcel 导出文件.md",
      "如何处理 CompletableFuture 中的两种异常(智能BI项目).md",
      "基于 Session 实现短信登录.md",
      "Synchronized 关键字详解.md",
      "Redission 解锁异常解决方案.md",
      "实现主题换肤( CSS 变量 + 类名切换).md",
      "SpringBoot 整合 Minio全流程（从安装 Minio 到应用）.md",
      "【Redis应用】UV统计.md",
      "《贯穿设计模式》第三方登录实践[附前后端完整过程及测试].md",
      "Websocket.+ Spring-SseEmitter3 实现讯飞星火Java客户端.md",
      "用布隆过滤器实现检查用户名是否存在(用户注册).md",
      "SpringSecurity 整合 Oauth2.md",
      "前端初始化 Ant Design Pro 笔记.md",
      "LiteFlow 编排式编程简单介绍.md",
      "基于 Redis 实现短信登录.md",
      "MySQL 一棵 B + 树可以存多少条数据？.md",
      "SpringBoot 整合 ELK 实现日志采集与监控.md",
      "基于自定义注解的 Redisson 分布式锁实现.md",
      "玩转异步编程利器 CompletableFuture.md",
      "通过 Windows 脚本执行打包操作.md",
      "阿里云对象存储 OSS.md",
      "后端 Spring Boot 万用模板使用.md",
      "使用 canal 实现增量订阅和消费.md",
      "SpringBoot + Quartz 简易定时任务.md",
      "String 的 intern() 方法.md",
      "MySQL 字符串日期格式转换.md",
      "fail-fast 机制是什么？.md",
      "十种 SQL 的写法.md",
      "MyBatis 整合多数据源.md",
      "1秒将本地SpringBoot项目jar包部署到Linux环境.md",
      "DDD 是什么？.md",
      "Oracle到MySQL函数替换方案汇总.md",
      "Springboot 引入 Nacos ( Windows 版).md",
      "利用局域网搭建虚拟机实现访问项目.md",
      "浅谈 cookie 和 session.md",
      "用 QQ 邮箱实现验证码功能.md",
      "Redis 实现文章点赞功能(附带前后端代码、数据库).md",
      "阿里云短信服务实现手机验证码.md",
      "【Ajax】异步通信.md",
      "【设计模式】七大设计原则.md",
      "文章评论功能前后端实现方案总结.md",
      "【版本控制】Git快速上手.md",
      "【Java基础】消灭魔法值-常量&枚举详述.md",
      "MySQL 的 Char 并不一定是定长.md",
      "TextCNN 文本分类模型在文章评论审核中的实现与部署.md",
      "理解 IO 多路复用.md",
      "ElasticSearch 基础概念与入门使用.md",
      "理解进程，线程，协程.md",
      "理解原码、反码、补码.md",
      "定义API并生成代码（ Go 微服务框架 Kratos ）.md",
      "使用对象存储实现文件上传下载.md",
      "MarkDown 文本解析成 HTML 并生成大纲.md",
      "10 分钟快速搞懂 Lambda 表达式.md",
      "SpringBoot 项目中快速引入 Rabbit MQ 通用做法.md",
      "OJ 竞赛排行榜统计逻辑设计与代码实现.md",
      "多语言代码沙箱的设计与实现(OJ 在线判题系统).md",
      "Java 8 新特性：Stream 流快速入门.md",
      "使用 NVM 快捷管理 Node 版本（Win版）.md",
      "Vue3 快速实现文件上传 OSS.md",
      "如何解决缓存击穿？.md",
      "RabbitMQ一死信队列介绍和应用.md",
      "详解 SpringBoot 自定义 Starter.md",
      "从聚合搜索项目视角入门 ElasticSearch.md",
      "常用的性能优化方法.md",
      "常用的存储优化方法.md",
      "Java 实现 GitHub 第三方登录详解.md",
      "伙伴匹配引入 GEO 实现搜索附近用户.md",
      "设计模式实践（OJ判题和聚合搜索).md",
      "模板引擎-Thymeleaf与Freemarker.md",
      "海量数据场景面试题：出现频率最高的 100 个词.md",
      "深入了解进程和线程：概念、区别和优化.md",
      "WebSocket 前后端联调使用.md",
      "并发问题的三大根源是什么？.md",
      "基于 GA 遗传算法的智能组题模块的设计与应用.md",
      "使用 AOP+自定义注解实现日志打印.md",
      "Hexo+Github+Netlify博客搭建教程.md",
      "什么是接口的幂等性，如何保证接口的幂等性？.md",
      "DTO转VO工具.md",
      "提示工程进阶技巧（大模型）.md",
      "MinIO+Docker 从零搭建一个文件存储服务.md",
       "MySQL8 绿色版安装.md",
      "IDEA+Docker远程部署SpringBoot项目.md",
      "函数式接口的使用.md",
      "面试超高频考点：HashMap 源码逐行解析.md",
      "MySQL基础知识：DDL、DML、DQL、DCL及TPL的使用.md",
      "SpringBoot通过自定义注解实现多数据源.md",
      "IDEA 同时关联 GitHub 和 Gitee 远程仓库.md",
      "缓存穿透、缓存击穿、缓存雪崩的场景以及解决方法.md",
      "状态机概念以及使用.md"
    ],
  },
];
