export default [
  "",
  {
    title: "知识碎片",
    collapsable: false,
    children: [
      "4 种方法，快速初始化 Java 项目.md",
      "使用后端代码生成器，提高开发效率.md",
      "前端必学的开发框架，Ant Design Pro.md",
      "后端如何编写单元测试？ .md",
      "后端项目经典分层架构介绍.md",
      "如何高效测试接口？自动生成接口文档.md",
      "开发企业微信群机器人，实现定时提醒.md",
      "如何解决数据查询为空的 Bug？.md",
      "Git 提交竟然还能这么用？.md",
      "【设计模式】装饰者模式，及其在JDK源码中的应用.md",
      "用四种锁实现加入队伍功能(伙伴匹配系统).md",
      "用@Validated注解实现非空校验.md",
      "使用第三方服务(宝塔)快速部署项目.md",
      "RESTful 接口实现与测试( Spring Boot ).md",
      "快速学会为开源项目做贡献.md",
      "整合Spring JDBC操作数据库.md",
      "Maven 中央仓库发包流程.md",
      "Nacos 配置中心搭建.md",
      "Bean 拷贝之 MapStruct.md",
      "使用 FreeMarker 模板引擎生成代码.md",
      "如何快速忽略 Git 文件提交？.md",
      "EasyExcel 导出文件.md",
      "如何处理 CompletableFuture 中的两种异常(智能BI项目).md",
      "基于 Session 实现短信登录.md",
      "Synchronized 关键字详解.md",
      "Redission 解锁异常解决方案.md",
      "实现主题换肤( CSS 变量 + 类名切换).md",
      "SpringBoot 整合 Minio全流程（从安装 Minio 到应用）.md",
      "【Redis应用】UV统计.md",
      "《贯穿设计模式》第三方登录实践[附前后端完整过程及测试].md",
      "Websocket.+ Spring-SseEmitter3 实现讯飞星火Java客户端.md",
      "用布隆过滤器实现检查用户名是否存在(用户注册).md",
      "SpringSecurity 整合 Oauth2.md",
      "前端初始化 Ant Design Pro 笔记.md",
      "LiteFlow 编排式编程简单介绍.md",
      "基于 Redis 实现短信登录.md",
      "MySQL 一棵 B + 树可以存多少条数据？.md",
      "SpringBoot 整合 ELK 实现日志采集与监控.md",
      "基于自定义注解的 Redisson 分布式锁实现.md",
      "玩转异步编程利器 CompletableFuture.md",
      "通过 Windows 脚本执行打包操作.md",
      "阿里云对象存储 OSS.md",
      "后端 Spring Boot 万用模板使用.md",
      "使用 canal 实现增量订阅和消费.md",
      "SpringBoot + Quartz 简易定时任务.md",
      "String 的 intern() 方法.md",
      "MySQL 字符串日期格式转换.md",
      "fail-fast 机制是什么？.md",
      "十种 SQL 的写法.md",
      "MyBatis 整合多数据源.md",
      "1秒将本地SpringBoot项目jar包部署到Linux环境.md",
      "DDD 是什么？.md",
      "Oracle到MySQL函数替换方案汇总.md"
    ],
  },
];
