export default [
  "",
  {
    title: "知识碎片",
    collapsable: false,
    children: [
      "4 种方法，快速初始化 Java 项目.md",
      "使用后端代码生成器，提高开发效率.md",
      "前端必学的开发框架，Ant Design Pro.md",
      "后端如何编写单元测试？ .md",
      "后端项目经典分层架构介绍.md",
      "如何高效测试接口？自动生成接口文档.md",
      "开发企业微信群机器人，实现定时提醒.md",
      "如何解决数据查询为空的 Bug？.md",
      "Git 提交竟然还能这么用？.md",
      "【设计模式】装饰者模式，及其在JDK源码中的应用.md",
      "用四种锁实现加入队伍功能(伙伴匹配系统).md",
      "用@Validated注解实现非空校验.md",
      "使用第三方服务(宝塔)快速部署项目.md",
      "RESTful 接口实现与测试( Spring Boot ).md",
      "快速学会为开源项目做贡献.md",
      "整合Spring JDBC操作数据库.md",
      "Maven 中央仓库发包流程.md",
      "Nacos 配置中心搭建.md",
      "Bean 拷贝之 MapStruct.md",
      "使用 FreeMarker 模板引擎生成代码.md",
      "如何快速忽略 Git 文件提交？.md",
    ],
  },
];
