export default [
  "",
  {
    title: "项目实战",
    collapsable: false,
    children: [
      "鱼皮项目学习建议（必读）.md",
      "AI 零代码应用生成平台（25 年最新）.md",
      "AI 超级智能体（25 年必学）.md",
      "智能协同云图库项目（25 年最新）.md",
      "面试刷题项目.md",
      "AI 答题应用平台.md",
      "代码生成器共享平台.md",
      "手写 RPC 框架.md",
      "OJ 判题系统.md",
      "智能 BI 平台.md",
      "聚合搜索平台.md",
      "API 开放平台.md",
      "伙伴匹配系统.md",
      "用户中心项目.md",
      "Java 后端万用项目模板.md",
      "前端万用项目模板.md",
    ],
  },
];
